main: "ch.laurinneff.skyfighters.SkyFighters"
version: "1.2.0-SNAPSHOT"
api-version: "1.14"
name: "SkyFighters"
author: "Laurin Neff"
description: "Fight in the sky!"
commands:
  skyfighters:
    description: "The Command for every SkyFighters Feature"
    aliases:
      - "sf"